-- ==============================================================================
-- ELEV8ED DATABASE SCHEMA (Supabase / PostgreSQL)
-- Target: Multi-tenant, Committee-centric Student Organization OS
-- ==============================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. USER PROFILES
-- Extends Supabase auth.users with student-specific attributes
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text not null,
  email text not null unique,
  college text,
  course text,
  year text,
  bio text,
  avatar_url text,
  skills text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. COMMITTEES
-- Top-level organization container. A user can belong to multiple committees.
create table if not exists public.committees (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  slug text unique,
  description text,
  college text not null,
  category text default 'Technical' not null,
  academic_year text default '2026-2027' not null,
  logo_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. DEPARTMENTS
-- Verticals within a committee (e.g. Technical, PR, Creatives, Logistics)
create table if not exists public.departments (
  id uuid default uuid_generate_v4() primary key,
  committee_id uuid references public.committees(id) on delete cascade not null,
  name text not null,
  description text,
  head_id uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(committee_id, name)
);

-- 4. COMMITTEE MEMBERSHIPS
-- Maps a user to a specific committee with a role and optional department
-- Role hierarchy: 'owner' > 'admin' > 'head' > 'member'
create table if not exists public.committee_members (
  id uuid default uuid_generate_v4() primary key,
  committee_id uuid references public.committees(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  department_id uuid references public.departments(id) on delete set null,
  role text check (role in ('owner', 'admin', 'head', 'member')) not null default 'member',
  title text default 'Member',
  status text check (status in ('active', 'inactive')) default 'active' not null,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(committee_id, user_id)
);

-- 5. INVITATIONS
-- Invitation tokens generated by admins to onboard members into committees
create table if not exists public.invitations (
  id uuid default uuid_generate_v4() primary key,
  committee_id uuid references public.committees(id) on delete cascade not null,
  email text,
  department_id uuid references public.departments(id) on delete set null,
  role text check (role in ('admin', 'head', 'member')) default 'member' not null,
  token text unique not null,
  status text check (status in ('pending', 'accepted', 'rejected', 'expired')) default 'pending' not null,
  invited_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone default (timezone('utc'::text, now()) + interval '7 days') not null
);

-- 6. TASKS
-- Core task management with status, priority, and assignees
create table if not exists public.tasks (
  id uuid default uuid_generate_v4() primary key,
  committee_id uuid references public.committees(id) on delete cascade not null,
  department_id uuid references public.departments(id) on delete set null,
  title text not null,
  description text,
  assigned_to uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  priority text check (priority in ('low', 'medium', 'high', 'urgent')) default 'medium' not null,
  status text check (status in ('todo', 'in_progress', 'completed', 'cancelled')) default 'todo' not null,
  due_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone
);

-- 7. EVENTS
-- Committee events, flagship fests, workshops, and internal meetings
create table if not exists public.events (
  id uuid default uuid_generate_v4() primary key,
  committee_id uuid references public.committees(id) on delete cascade not null,
  department_id uuid references public.departments(id) on delete set null,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  venue text not null,
  status text check (status in ('draft', 'upcoming', 'ongoing', 'completed', 'cancelled')) default 'upcoming' not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. ANNOUNCEMENTS
-- Official notices broadcasted to the entire committee or specific department
create table if not exists public.announcements (
  id uuid default uuid_generate_v4() primary key,
  committee_id uuid references public.committees(id) on delete cascade not null,
  department_id uuid references public.departments(id) on delete set null,
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id) on delete set null,
  priority text check (priority in ('low', 'normal', 'urgent')) default 'normal' not null,
  audience text check (audience in ('all', 'department')) default 'all' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. ACTIVITY LOGS
-- Centralized immutable audit trail for committee operations
create table if not exists public.activity_logs (
  id uuid default uuid_generate_v4() primary key,
  committee_id uuid references public.committees(id) on delete cascade not null,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Ensures strict multi-tenant isolation so committee members only see their data
-- ==============================================================================

alter table public.profiles enable row level security;
alter table public.committees enable row level security;
alter table public.departments enable row level security;
alter table public.committee_members enable row level security;
alter table public.invitations enable row level security;
alter table public.tasks enable row level security;
alter table public.events enable row level security;
alter table public.announcements enable row level security;
alter table public.activity_logs enable row level security;

-- Profiles: Anyone authenticated can read profiles; users can update their own profile
create policy "Public profiles are viewable by authenticated users"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id);

-- Committees: Viewable if user is a member of the committee
create policy "Members can view their committees"
  on public.committees for select
  to authenticated
  using (
    exists (
      select 1 from public.committee_members
      where committee_members.committee_id = committees.id
      and committee_members.user_id = auth.uid()
    )
  );

create policy "Authenticated users can create committees"
  on public.committees for insert
  to authenticated
  with check (auth.uid() = created_by);

create policy "Owners and Admins can update their committees"
  on public.committees for update
  to authenticated
  using (
    exists (
      select 1 from public.committee_members
      where committee_members.committee_id = committees.id
      and committee_members.user_id = auth.uid()
      and committee_members.role in ('owner', 'admin')
    )
  );

-- Committee Members: Viewable by fellow committee members
create policy "Members can view committee members"
  on public.committee_members for select
  to authenticated
  using (
    exists (
      select 1 from public.committee_members as cm
      where cm.committee_id = committee_members.committee_id
      and cm.user_id = auth.uid()
    )
  );

-- Tasks: Viewable by committee members; creatable by members/admins
create policy "Members can view committee tasks"
  on public.tasks for select
  to authenticated
  using (
    exists (
      select 1 from public.committee_members
      where committee_members.committee_id = tasks.committee_id
      and committee_members.user_id = auth.uid()
    )
  );

create policy "Members can create tasks in their committee"
  on public.tasks for insert
  to authenticated
  with check (
    exists (
      select 1 from public.committee_members
      where committee_members.committee_id = tasks.committee_id
      and committee_members.user_id = auth.uid()
    )
  );

create policy "Assigned users and admins can update tasks"
  on public.tasks for update
  to authenticated
  using (
    assigned_to = auth.uid() or
    exists (
      select 1 from public.committee_members
      where committee_members.committee_id = tasks.committee_id
      and committee_members.user_id = auth.uid()
      and committee_members.role in ('owner', 'admin', 'head')
    )
  );
